"""
Phoenix Bot — Climax Reversal Detector with Secondary-Test Confirmation

HARD ARCHITECTURAL RULE: climax bar generates a WARNING only, NEVER an entry
signal. Entry is ALWAYS on the secondary-test bar (2-5 bars later) with its
own confirmation criteria.

Research basis (2026):
- 40% of stocks experience catastrophic -70% drawdowns they never recover from
- Knife-catching has no sustainable edge; secondary-test entry has ~65-70% WR with filters
- Wyckoff methodology: Selling Climax → Automatic Rally → Secondary Test
- The PROFESSIONAL path: wait for confirmation, accept 30-40% of move gone, avoid blowup

Climax criteria (ALL must fire same bar):
1. Volume ≥ 2× 20-bar average
2. Range ≥ 1.5× ATR(14)
3. Close position: upper 50% of range (sell climax) or lower 50% (buy climax)
4. Rejection wick > 50% of range on absorption side
5. Session CVD at extreme (most negative for sell climax, most positive for buy)

Secondary test entry criteria (generated 1-5 bars after warning):
1. Price retests climax extreme on LOWER volume (< 60% of climax bar)
2. CVD divergence (price LL but CVD HL for long setup)
3. Structural BOS (breaks most recent opposite pivot)
"""

from __future__ import annotations

import logging
from collections import deque
from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional

logger = logging.getLogger("ReversalDetector")


# ─── Thresholds (configurable via regime_params later) ─────────────────
CLIMAX_VOL_MULT = 2.0              # Volume ≥ 2× 20-bar MA
CLIMAX_RANGE_ATR_MULT = 1.5        # Range ≥ 1.5× ATR14
CLIMAX_CLOSE_POS_THRESHOLD = 0.5   # Close in top/bottom 50%
CLIMAX_WICK_RATIO = 0.5            # Rejection wick > 50% of range

SECONDARY_TEST_MIN_BARS = 1        # At least 1 bar after climax
SECONDARY_TEST_MAX_BARS = 5        # Window closes after 5 bars
SECONDARY_TEST_VOL_RATIO = 0.6     # Retest vol < 60% of climax vol


@dataclass
class ClimaxWarning:
    """A confirmed climax bar — NOT an entry signal."""
    direction: str           # "BULLISH_REVERSAL" (selling climax) or "BEARISH_REVERSAL" (buying climax)
    climax_ts: datetime
    climax_bar_idx: int
    climax_extreme: float    # Low of sell climax or high of buy climax
    climax_volume: float
    climax_cvd: float        # Session CVD at climax time
    reasons: list[str]       # Human-readable criteria that fired
    active: bool = True      # Becomes False after secondary test window closes

    def bars_since_climax(self, current_bar_idx: int) -> int:
        return current_bar_idx - self.climax_bar_idx


@dataclass
class ReversalSignal:
    """A VALID entry signal generated by secondary-test confirmation."""
    ts: datetime
    bar_idx: int
    direction: str           # "LONG" or "SHORT"
    entry_price: float       # Close of secondary-test bar
    stop_price: float        # Climax extreme +/- 2 ticks
    climax_warning: ClimaxWarning  # The climax this test confirms
    confirmation_reasons: list[str]


class ReversalDetector:
    """
    Stateful climax + secondary-test detector.
    Call update(bar, atr, session_cvd) on each completed 1m bar.
    Returns either:
      - ClimaxWarning (new climax detected) — NO ENTRY SIGNAL
      - ReversalSignal (valid secondary-test entry) — use for actual trade
      - None (no event)
    """

    def __init__(self, volume_ma_window: int = 20):
        self.volume_ma_window = volume_ma_window
        self.recent_volumes: deque[float] = deque(maxlen=volume_ma_window)
        self.active_warnings: list[ClimaxWarning] = []
        self.recent_cvd_window: deque[float] = deque(maxlen=60)  # Track CVD extremes

    def _volume_ma(self) -> float:
        if not self.recent_volumes:
            return 0.0
        return sum(self.recent_volumes) / len(self.recent_volumes)

    def _detect_climax(self, bar, atr: float, session_cvd: float,
                        bar_idx: int) -> Optional[ClimaxWarning]:
        """Check if THIS bar is a climax. Returns ClimaxWarning or None."""
        if len(self.recent_volumes) < 10:
            return None  # Not enough history
        if atr <= 0:
            return None

        vol_ma = self._volume_ma()
        bar_range = bar.high - bar.low
        if bar_range <= 0:
            return None

        # Criterion 1: extreme volume
        if bar.volume < vol_ma * CLIMAX_VOL_MULT:
            return None
        # Criterion 2: wide range
        if bar_range < atr * CLIMAX_RANGE_ATR_MULT:
            return None

        # Classify direction: close position + wick
        close_pos = (bar.close - bar.low) / bar_range  # 0 = closed at low, 1 = closed at high
        upper_wick = bar.high - max(bar.open, bar.close)
        lower_wick = min(bar.open, bar.close) - bar.low
        upper_wick_ratio = upper_wick / bar_range
        lower_wick_ratio = lower_wick / bar_range

        reasons = []
        reasons.append(f"volume {bar.volume / vol_ma:.1f}× MA20")
        reasons.append(f"range {bar_range / atr:.1f}× ATR")

        # SELLING CLIMAX (long setup pending secondary test)
        if close_pos >= CLIMAX_CLOSE_POS_THRESHOLD and lower_wick_ratio >= CLIMAX_WICK_RATIO:
            # Check CVD at extreme
            if self.recent_cvd_window:
                cvd_min = min(self.recent_cvd_window)
                if session_cvd <= cvd_min * 0.95:  # Near-extreme negative
                    reasons.append(f"close upper {close_pos:.0%}")
                    reasons.append(f"lower wick {lower_wick_ratio:.0%}")
                    reasons.append(f"CVD at session extreme ({session_cvd:.0f})")
                    return ClimaxWarning(
                        direction="BULLISH_REVERSAL",
                        climax_ts=bar.ts if hasattr(bar, "ts") else datetime.now(),
                        climax_bar_idx=bar_idx,
                        climax_extreme=bar.low,
                        climax_volume=bar.volume,
                        climax_cvd=session_cvd,
                        reasons=reasons,
                    )

        # BUYING CLIMAX (short setup pending secondary test)
        if close_pos <= (1 - CLIMAX_CLOSE_POS_THRESHOLD) and upper_wick_ratio >= CLIMAX_WICK_RATIO:
            if self.recent_cvd_window:
                cvd_max = max(self.recent_cvd_window)
                if session_cvd >= cvd_max * 0.95:
                    reasons.append(f"close lower {1-close_pos:.0%}")
                    reasons.append(f"upper wick {upper_wick_ratio:.0%}")
                    reasons.append(f"CVD at session extreme (+{session_cvd:.0f})")
                    return ClimaxWarning(
                        direction="BEARISH_REVERSAL",
                        climax_ts=bar.ts if hasattr(bar, "ts") else datetime.now(),
                        climax_bar_idx=bar_idx,
                        climax_extreme=bar.high,
                        climax_volume=bar.volume,
                        climax_cvd=session_cvd,
                        reasons=reasons,
                    )

        return None

    def _check_secondary_test(self, bar, session_cvd: float,
                               bar_idx: int) -> Optional[ReversalSignal]:
        """
        Check each active warning to see if THIS bar qualifies as secondary test.
        Returns a ReversalSignal if confirmed, else None.
        """
        for warning in self.active_warnings[:]:  # Iterate over copy
            bars_since = warning.bars_since_climax(bar_idx)

            # Window check
            if bars_since < SECONDARY_TEST_MIN_BARS:
                continue
            if bars_since > SECONDARY_TEST_MAX_BARS:
                warning.active = False
                continue

            reasons = []

            if warning.direction == "BULLISH_REVERSAL":
                # Secondary test: price retested the climax low on lower volume
                # Must form a higher low (not re-break the climax)
                if bar.low <= warning.climax_extreme:
                    # Re-broke the low — disqualify as failed test
                    warning.active = False
                    continue
                # Volume check
                if bar.volume >= warning.climax_volume * SECONDARY_TEST_VOL_RATIO:
                    continue  # Too heavy — not a proper test
                # CVD divergence: price made HL but CVD higher than climax
                if session_cvd <= warning.climax_cvd:
                    continue
                # Confirmed
                reasons.append(f"HL at {bar.low:.2f} > climax low {warning.climax_extreme:.2f}")
                reasons.append(f"retest vol {bar.volume / warning.climax_volume:.0%} of climax")
                reasons.append(f"CVD divergence: {session_cvd:.0f} > climax {warning.climax_cvd:.0f}")
                signal = ReversalSignal(
                    ts=bar.ts if hasattr(bar, "ts") else datetime.now(),
                    bar_idx=bar_idx,
                    direction="LONG",
                    entry_price=bar.close,
                    stop_price=warning.climax_extreme - 0.5,  # 2 ticks below climax low
                    climax_warning=warning,
                    confirmation_reasons=reasons,
                )
                warning.active = False
                return signal

            elif warning.direction == "BEARISH_REVERSAL":
                if bar.high >= warning.climax_extreme:
                    warning.active = False
                    continue
                if bar.volume >= warning.climax_volume * SECONDARY_TEST_VOL_RATIO:
                    continue
                if session_cvd >= warning.climax_cvd:
                    continue
                reasons.append(f"LH at {bar.high:.2f} < climax high {warning.climax_extreme:.2f}")
                reasons.append(f"retest vol {bar.volume / warning.climax_volume:.0%} of climax")
                reasons.append(f"CVD divergence: {session_cvd:.0f} < climax {warning.climax_cvd:.0f}")
                signal = ReversalSignal(
                    ts=bar.ts if hasattr(bar, "ts") else datetime.now(),
                    bar_idx=bar_idx,
                    direction="SHORT",
                    entry_price=bar.close,
                    stop_price=warning.climax_extreme + 0.5,
                    climax_warning=warning,
                    confirmation_reasons=reasons,
                )
                warning.active = False
                return signal

        # Expire stale warnings
        self.active_warnings = [w for w in self.active_warnings if w.active]
        return None

    def update(self, bar, atr: float, session_cvd: float, bar_idx: int
               ) -> tuple[Optional[ClimaxWarning], Optional[ReversalSignal]]:
        """
        Main entry point. Returns (warning_if_new, signal_if_confirmed).
        Only ONE of these fires per bar (never both).
        """
        # First: check if active warnings have valid secondary tests on this bar
        signal = self._check_secondary_test(bar, session_cvd, bar_idx)

        # Then: look for NEW climax bars (independent of signal generation)
        # Don't treat the signal-confirming bar as its own new climax
        new_warning = None
        if signal is None:
            new_warning = self._detect_climax(bar, atr, session_cvd, bar_idx)
            if new_warning:
                self.active_warnings.append(new_warning)
                logger.info(f"[CLIMAX WARNING] {new_warning.direction} at {new_warning.climax_extreme:.2f} "
                            f"- {', '.join(new_warning.reasons)} - entry requires secondary test")

        # Update rolling windows AFTER detection (so current bar doesn't bias its own MA)
        self.recent_volumes.append(bar.volume)
        self.recent_cvd_window.append(session_cvd)

        return (new_warning, signal)

    def get_state(self) -> dict:
        """Dashboard / market snapshot."""
        return {
            "active_warnings_count": len([w for w in self.active_warnings if w.active]),
            "active_warnings": [
                {
                    "direction": w.direction,
                    "climax_extreme": w.climax_extreme,
                    "climax_volume": w.climax_volume,
                    "bars_ago": w.bars_since_climax(len(self.recent_volumes)),
                }
                for w in self.active_warnings if w.active
            ],
        }
