"""
Phoenix Bot -- The Wolf: Multi-Agent Strategy Factory

Three agents collaborate in a loop to generate, validate, and refine strategies:
  Scout (Idea) -> Engineer (Factor) -> Judge (Eval)
  FAIL -> feedback -> Scout (max 3 loops) | PASS -> store

Usage:
  python -m tools.strategy_factory --hunt 10
  python -m tools.strategy_factory --hunt 5 --focus "FVG"
  python -m tools.strategy_factory --leaderboard
  python -m tools.strategy_factory --metrics
"""

import ast, json, logging, os, re, sys, time, argparse
from datetime import datetime
from typing import Any

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
logger = logging.getLogger("TheWolf")

# -- Valid market_data keys --------------------------------------------------
VALID_MARKET_KEYS = [
    "price", "bid", "ask", "vwap", "cvd", "ema9", "ema21", "atr_1m", "atr_5m",
    "tf_bias", "tf_votes_bullish", "tf_votes_bearish",
    "bar_delta", "bar_buy_vol", "bar_sell_vol",
    "dom_bid_stack", "dom_ask_stack", "dom_imbalance", "dom_bid_heavy", "dom_ask_heavy",
    "rsi", "rsi_divergence", "htf_patterns",
    "smc_structure", "smc_recent", "hmm_regime", "hmm_confidence",
    "candlestick_patterns", "candlestick_confluence",
    "cot", "intermarket", "calendar_risk",
]
MARKET_KEYS_DOC = ", ".join(VALID_MARKET_KEYS)

STRATEGY_TEMPLATE = '''"""
Phoenix Bot -- AI-Generated Strategy: {name}
Generated by The Wolf (MAS)
Timestamp: {timestamp}
Focus: {focus}
Regime: {regime}
Loops: {loops}
Review Score: {review_score}
"""

from strategies.base_strategy import BaseStrategy, Signal


class {class_name}(BaseStrategy):
    name = "{snake_name}"

    def evaluate(self, market: dict, bars_5m: list, bars_1m: list,
                 session_info: dict) -> Signal | None:
{code_body}
'''

HYPOTHESIS_PROMPT = """You are a quant strategist for MNQ (Micro Nasdaq) futures on 5m bars.

{rag_context}
{feedback_block}
Generate a specific, testable hypothesis. {focus_instruction}

Respond ONLY with valid JSON (no markdown):
{{"name":"descriptive name","regime":"TRENDING|RANGING|VOLATILE|ALL",\
"entry_conditions":"measurable conditions","direction_logic":"LONG vs SHORT logic",\
"stop_ticks":8,"target_rr":1.5,"max_hold_minutes":15,\
"confluence_required":"what must agree","why_it_works":"reasoning",\
"failure_modes":"what invalidates it"}}

Available keys: {market_keys}
CRITICAL: Only reference listed keys."""

CODE_GEN_PROMPT = """Convert this hypothesis into a Python method body for evaluate().

Hypothesis: {hypothesis_json}

Signature: def evaluate(self, market: dict, bars_5m: list, bars_1m: list, session_info: dict) -> Signal | None:
Keys: {market_keys}
bars_5m/bars_1m: list of Bar (.open .high .low .close .volume)
Signal(direction, stop_ticks, target_rr, confidence, entry_score, strategy, reason, confluences)
  direction="LONG"|"SHORT", stop_ticks=int(6-12), target_rr=float(1.5-2.5),
  confidence=0-100, entry_score=0-60, strategy=self.name, reason=str, confluences=list[str]

RULES: Return Signal or None. Use .get() with defaults. No imports. 8-space indent.
No markdown fences. Under 80 lines. Raw Python only."""

INDICATOR_TOKENS = ("ema", "rsi", "atr", "vwap", "cvd", "smc", "hmm",
                    "dom", "delta", "macd", "bb", "stoch")

DEFAULT_TOPICS = [
    "momentum breakout", "mean reversion at VWAP", "fair value gap fill",
    "liquidity sweep reversal", "order block bounce", "EMA crossover with volume",
    "RSI divergence entry", "opening range breakout", "DOM imbalance scalp",
    "trend following with ATR", "CVD divergence reversal", "VWAP pullback trending",
    "range fade initial balance", "hammer at support", "engulfing with DOM",
    "pin bar reversal", "inside bar breakout", "three soldiers momentum",
    "stochastic oversold bounce", "SMC structure break",
]


class TheWolf:
    """Multi-Agent Strategy Factory -- 'The Wolf'

    Three agents collaborate to generate, validate, and refine
    trading strategies. Named after the fixer -- it gets the job done.
    """

    def __init__(self):
        self._api_key = os.environ.get("ANTHROPIC_API_KEY", "")
        base = os.path.join(os.path.dirname(__file__), "..")
        self._strategies_dir = os.path.join(base, "generated_strategies")
        self._hand_dir = os.path.join(base, "strategies")
        self._registry_path = os.path.join(self._strategies_dir, "registry.json")
        os.makedirs(self._strategies_dir, exist_ok=True)
        self._registry = self._load_registry()
        self._metrics: dict[str, Any] = {
            "total_attempts": 0, "total_approved": 0, "total_rejected": 0,
            "common_failures": {}, "avg_loops_to_approve": 0.0, "_loop_counts": [],
        }
        self._reviewer = self._init_reviewer()
        self._rag = self._init_rag()

    # -- Bootstrap -----------------------------------------------------------

    def _load_registry(self) -> dict:
        try:
            with open(self._registry_path, "r") as f:
                return json.load(f)
        except (FileNotFoundError, json.JSONDecodeError):
            return {"strategies": [], "generated_count": 0, "last_run": None}

    def _save_registry(self):
        with open(self._registry_path, "w") as f:
            json.dump(self._registry, f, indent=2)

    @staticmethod
    def _init_reviewer():
        try:
            from tools.strategy_reviewer import StrategyReviewer
            r = StrategyReviewer()
            logger.info("[WOLF] StrategyReviewer loaded")
            return r
        except Exception as e:
            logger.warning("[WOLF] Reviewer unavailable: %s", e)
            return None

    @staticmethod
    def _init_rag():
        try:
            from core.knowledge_rag import KnowledgeRAG
            r = KnowledgeRAG()
            logger.info("[WOLF] KnowledgeRAG loaded")
            return r
        except Exception as e:
            logger.warning("[WOLF] RAG unavailable: %s", e)
            return None

    # -- Claude API ----------------------------------------------------------

    def _call_claude(self, prompt: str, max_tokens: int = 2000) -> str:
        try:
            import anthropic
            client = anthropic.Anthropic(api_key=self._api_key)
            resp = client.messages.create(
                model="claude-sonnet-4-20250514", max_tokens=max_tokens,
                messages=[{"role": "user", "content": prompt}],
            )
            return resp.content[0].text
        except ImportError:
            import urllib.request
            data = json.dumps({
                "model": "claude-sonnet-4-20250514", "max_tokens": max_tokens,
                "messages": [{"role": "user", "content": prompt}],
            }).encode()
            req = urllib.request.Request(
                "https://api.anthropic.com/v1/messages", data=data,
                headers={"Content-Type": "application/json",
                         "x-api-key": self._api_key, "anthropic-version": "2023-06-01"},
            )
            result = json.loads(urllib.request.urlopen(req, timeout=60).read().decode())
            return result["content"][0]["text"]

    # -- RAG helper ----------------------------------------------------------

    def _get_rag_context(self, focus: str = "") -> str:
        if self._rag:
            try:
                results = self._rag.query(focus or "profitable MNQ futures strategy", n_results=5)
                if results:
                    return "Relevant knowledge:\n" + "\n".join(
                        f"- {r['title']}: {r['content']}" for r in results)
            except Exception as e:
                logger.warning("[SCOUT] RAG failed: %s", e)
        return "Use standard technical analysis principles for MNQ futures."

    # -- Agent 1: The Scout (Idea Agent) -------------------------------------

    def _idea_agent(self, focus: str, feedback: dict | None = None) -> dict:
        """Generate or refine a market hypothesis."""
        logger.info("[SCOUT] Generating hypothesis | focus=%s feedback=%s", focus, feedback is not None)
        rag = self._get_rag_context(focus)
        focus_inst = f"Focus on: {focus}" if focus else "Choose any high-edge setup."
        fb_block = ""
        if feedback:
            lines = ["Previous attempt REJECTED. Feedback:"]
            for persona, text in feedback.items():
                lines.append(f"  {persona}: {text}")
            lines.append("Generate an IMPROVED hypothesis addressing these issues.")
            fb_block = "\n".join(lines)

        prompt = HYPOTHESIS_PROMPT.format(
            rag_context=rag, feedback_block=fb_block,
            focus_instruction=focus_inst, market_keys=MARKET_KEYS_DOC)
        resp = self._call_claude(prompt, max_tokens=1500)
        time.sleep(1)

        start, end = resp.find("{"), resp.rfind("}") + 1
        if start >= 0 and end > start:
            hyp = json.loads(resp[start:end])
            logger.info("[SCOUT] Hypothesis: %s | regime=%s", hyp.get("name"), hyp.get("regime"))
            return hyp
        raise ValueError("Scout failed to produce valid JSON")

    # -- Agent 2: The Engineer (Factor Agent) --------------------------------

    def _factor_agent(self, hypothesis: dict) -> str | None:
        """Write executable code and validate originality."""
        logger.info("[ENGINEER] Coding: %s", hypothesis.get("name"))
        prompt = CODE_GEN_PROMPT.format(
            hypothesis_json=json.dumps(hypothesis, indent=2), market_keys=MARKET_KEYS_DOC)
        resp = self._call_claude(prompt, max_tokens=2000)
        time.sleep(1)

        code = resp
        if "```python" in code:
            code = code.split("```python")[1].split("```")[0]
        elif "```" in code:
            code = code.split("```")[1].split("```")[0]
        code = code.strip()

        ok, reason = self._ast_safety_check(code)
        if not ok:
            logger.warning("[ENGINEER] Safety FAIL: %s", reason)
            return None
        ok, reason = self._originality_check(code)
        if not ok:
            logger.warning("[ENGINEER] Originality FAIL: %s", reason)
            return None
        logger.info("[ENGINEER] Code validated")
        return code

    def _ast_safety_check(self, code: str) -> tuple[bool, str]:
        """No imports, no file I/O, no exec/eval."""
        wrapped = f"def evaluate(self, market, bars_5m, bars_1m, session_info):\n{code}"
        try:
            tree = ast.parse(wrapped)
        except SyntaxError as e:
            return False, f"Syntax error: {e}"
        for node in ast.walk(tree):
            if isinstance(node, (ast.Import, ast.ImportFrom)):
                return False, f"Import: {ast.dump(node)}"
            if isinstance(node, ast.Call):
                if isinstance(node.func, ast.Name) and node.func.id in (
                        "open", "exec", "eval", "__import__", "compile", "input", "exit"):
                    return False, f"Disallowed: {node.func.id}"
                if isinstance(node.func, ast.Attribute) and node.func.attr in (
                        "system", "popen", "remove", "rmdir", "write", "unlink"):
                    return False, f"Disallowed: {node.func.attr}"
            if isinstance(node, ast.While) and isinstance(node.test, ast.Constant) and node.test.value is True:
                return False, "Infinite loop"
        return True, "OK"

    def _originality_check(self, code: str) -> tuple[bool, str]:
        """AST fingerprint comparison against all existing strategies."""
        new_fp = self._fingerprint(code)
        if not new_fp["indicators"] and not new_fp["market_keys"]:
            return True, "Trivial"
        for d in (self._strategies_dir, self._hand_dir):
            if not os.path.isdir(d):
                continue
            for fn in os.listdir(d):
                if not fn.endswith(".py") or fn.startswith("__"):
                    continue
                try:
                    with open(os.path.join(d, fn), "r", encoding="utf-8") as f:
                        old_fp = self._fingerprint(f.read())
                    if self._overlap(new_fp, old_fp) > 0.80:
                        return False, f">80% overlap with {fn}"
                except Exception:
                    continue
        return True, "Original"

    @staticmethod
    def _fingerprint(code: str) -> dict[str, set]:
        fp: dict[str, set] = {"indicators": set(), "comparisons": set(),
                               "thresholds": set(), "market_keys": set()}
        try:
            tree = ast.parse(code)
        except SyntaxError:
            try:
                tree = ast.parse(f"def _f():\n{code}")
            except SyntaxError:
                return fp
        for node in ast.walk(tree):
            if isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute):
                if (node.func.attr == "get" and node.args
                        and isinstance(node.args[0], ast.Constant)
                        and isinstance(node.args[0].value, str)):
                    fp["market_keys"].add(node.args[0].value)
            if isinstance(node, ast.Subscript):
                if isinstance(node.slice, ast.Constant) and isinstance(node.slice.value, str):
                    fp["market_keys"].add(node.slice.value)
            if isinstance(node, ast.Compare):
                for op in node.ops:
                    fp["comparisons"].add(type(op).__name__)
                for c in node.comparators:
                    if isinstance(c, ast.Constant) and isinstance(c.value, (int, float)):
                        fp["thresholds"].add(c.value)
            if isinstance(node, ast.Name):
                nl = node.id.lower()
                if any(t in nl for t in INDICATOR_TOKENS):
                    fp["indicators"].add(node.id)
        return fp

    @staticmethod
    def _overlap(a: dict[str, set], b: dict[str, set]) -> float:
        total = matching = 0
        for k in ("indicators", "comparisons", "thresholds", "market_keys"):
            sa, sb = a.get(k, set()), b.get(k, set())
            if not sa and not sb:
                continue
            total += len(sa | sb)
            matching += len(sa & sb)
        return matching / total if total else 0.0

    # -- Agent 3: The Judge (Eval Agent) -------------------------------------

    def _eval_agent(self, code: str, hypothesis: dict) -> dict:
        """Review via multi-persona reviewer or fall back to AST-only."""
        name = hypothesis.get("name", "unknown")
        logger.info("[JUDGE] Reviewing: %s", name)

        if self._reviewer:
            try:
                snake = self._to_snake(name)
                full_src = STRATEGY_TEMPLATE.format(
                    name=name, timestamp=datetime.now().isoformat(),
                    focus="", regime=hypothesis.get("regime", "ALL"),
                    loops=0, review_score=0,
                    class_name=self._to_class(snake), snake_name=snake, code_body=code)
                r = self._reviewer.review(full_src, hypothesis)
                logger.info("[JUDGE] %s | score=%.2f",
                            "APPROVED" if r["approved"] else "REJECTED", r.get("score", 0))
                return {"approved": r["approved"], "feedback": r.get("feedback", {}),
                        "score": r.get("score", 0.0), "votes": r.get("votes", {})}
            except Exception as e:
                logger.warning("[JUDGE] Reviewer error: %s -- AST fallback", e)

        logger.info("[JUDGE] No reviewer -- auto-approve via AST")
        return {"approved": True, "feedback": {"note": "Auto-approved (no reviewer)"},
                "score": 0.0, "votes": {}}

    # -- The Hunt (main loop) ------------------------------------------------

    def hunt(self, focus: str = "", max_loops: int = 3) -> dict | None:
        """Run the full MAS loop for one strategy."""
        logger.info("[WOLF] ===== HUNT ===== focus=%s max_loops=%d", focus, max_loops)
        self._metrics["total_attempts"] += 1
        prev_fb: dict | None = None

        for loop in range(max_loops):
            logger.info("[WOLF] Loop %d/%d", loop + 1, max_loops)
            try:
                hyp = self._idea_agent(focus, feedback=prev_fb)
                code = self._factor_agent(hyp)
                if code is None:
                    prev_fb = {"Engineer": "Code rejected (safety or originality)"}
                    self._record_failure("Engineer rejected")
                    continue

                result = self._eval_agent(code, hyp)
                if result["approved"]:
                    entry = self._store(code, hyp, result, loop + 1)
                    self._metrics["total_approved"] += 1
                    self._metrics["_loop_counts"].append(loop + 1)
                    self._update_avg()
                    logger.info("[WOLF] KILL: %s in %d loops", hyp.get("name"), loop + 1)
                    return entry

                prev_fb = result.get("feedback", {})
                self._metrics["total_rejected"] += 1
                self._record_failure("Review rejected")
                logger.info("[WOLF] Rejected -- recycling feedback to Scout")
            except Exception as e:
                logger.error("[WOLF] Loop %d error: %s", loop + 1, e)
                prev_fb = {"error": str(e)}
                self._record_failure(str(e)[:60])

        logger.warning("[WOLF] MISS: exhausted %d loops", max_loops)
        return None

    def pack_hunt(self, count: int = 10, focus: str = "") -> list:
        """Generate multiple strategies (batch mode)."""
        logger.info("[WOLF] Pack hunt: %d strategies, focus=%s", count, focus)
        results = []
        for i in range(count):
            topic = focus if focus else DEFAULT_TOPICS[i % len(DEFAULT_TOPICS)]
            print(f"\n[{i + 1}/{count}] Hunting: {topic}")
            entry = self.hunt(focus=topic)
            if entry:
                results.append(entry)
                print(f"  KILL: {entry['name']}")
            else:
                print(f"  MISS")
        print(f"\nPack hunt: {len(results)}/{count} approved")
        return results

    # -- Storage -------------------------------------------------------------

    def _store(self, code: str, hyp: dict, review: dict, loops: int) -> dict:
        name = hyp.get("name", f"ai_strategy_{int(time.time())}")
        snake = self._to_snake(name)
        cls = self._to_class(snake)
        score = review.get("score", 0.0)

        src = STRATEGY_TEMPLATE.format(
            name=name, timestamp=datetime.now().isoformat(),
            focus=hyp.get("focus", "general"), regime=hyp.get("regime", "ALL"),
            loops=loops, review_score=score,
            class_name=cls, snake_name=snake, code_body=code)

        path = os.path.join(self._strategies_dir, f"{snake}.py")
        with open(path, "w", encoding="utf-8") as f:
            f.write(src)

        entry = {
            "name": name, "snake_name": snake, "class_name": cls,
            "filename": f"{snake}.py", "regime": hyp.get("regime", "ALL"),
            "hypothesis": hyp, "review_score": score,
            "review_votes": review.get("votes", {}), "loops_to_approve": loops,
            "generated_at": datetime.now().isoformat(),
            "validated": True, "backtested": False, "backtest_results": None,
        }
        self._registry["strategies"].append(entry)
        self._registry["generated_count"] += 1
        self._registry["last_run"] = datetime.now().isoformat()
        self._save_registry()
        logger.info("[WOLF] Stored: %s (loops=%d score=%.2f)", path, loops, score)
        return entry

    # -- Metrics -------------------------------------------------------------

    def _record_failure(self, reason: str):
        k = reason[:60]
        self._metrics["common_failures"][k] = self._metrics["common_failures"].get(k, 0) + 1

    def _update_avg(self):
        lc = self._metrics["_loop_counts"]
        self._metrics["avg_loops_to_approve"] = sum(lc) / len(lc) if lc else 0.0

    def get_metrics(self) -> dict:
        m = {k: v for k, v in self._metrics.items() if not k.startswith("_")}
        total = m["total_approved"] + m["total_rejected"]
        m["approval_rate"] = f"{m['total_approved'] / total:.0%}" if total else "N/A"
        return m

    def get_leaderboard(self) -> list:
        strats = self._registry.get("strategies", [])
        return sorted(strats, key=lambda s: (
            s.get("review_score", 0),
            (s.get("backtest_results") or {}).get("win_rate", 0),
        ), reverse=True)

    def to_dict(self) -> dict:
        return {
            "strategies_count": len(self._registry.get("strategies", [])),
            "metrics": self.get_metrics(), "last_run": self._registry.get("last_run"),
            "reviewer_available": self._reviewer is not None,
            "rag_available": self._rag is not None,
        }

    # -- Helpers -------------------------------------------------------------

    @staticmethod
    def _to_snake(name: str) -> str:
        return re.sub(r"[^a-z0-9_]", "", name.lower().replace(" ", "_").replace("-", "_"))[:40]

    @staticmethod
    def _to_class(snake: str) -> str:
        return "".join(w.capitalize() for w in snake.split("_") if w)


# -- CLI ---------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="The Wolf -- Multi-Agent Strategy Factory")
    parser.add_argument("--hunt", type=int, help="Number of strategies to generate")
    parser.add_argument("--focus", type=str, default="", help="Strategy focus/theme")
    parser.add_argument("--leaderboard", action="store_true")
    parser.add_argument("--metrics", action="store_true")
    args = parser.parse_args()

    try:
        from dotenv import load_dotenv
        load_dotenv(os.path.join(os.path.dirname(__file__), "..", ".env"))
    except ImportError:
        pass

    wolf = TheWolf()

    if args.leaderboard:
        strats = wolf.get_leaderboard()
        print(f"\n{'=' * 70}")
        print(f"  The Wolf -- Leaderboard ({len(strats)} strategies)")
        print(f"{'=' * 70}")
        for i, s in enumerate(strats, 1):
            bt = s.get("backtest_results")
            wr = f"{bt['win_rate']:.0f}%" if bt else "n/a"
            print(f"  {i:3d}. {s['name'][:38]:<40s} score={s.get('review_score',0):<5.2f} "
                  f"WR={wr:<6s} regime={s.get('regime','?')}")
        return

    if args.metrics:
        m = wolf.get_metrics()
        print(f"\n  The Wolf -- Metrics")
        print(f"  Attempts: {m['total_attempts']}  Approved: {m['total_approved']}  "
              f"Rejected: {m['total_rejected']}  Rate: {m['approval_rate']}  "
              f"Avg loops: {m['avg_loops_to_approve']:.1f}")
        if m["common_failures"]:
            print("  Failures:")
            for r, c in sorted(m["common_failures"].items(), key=lambda x: -x[1]):
                print(f"    [{c}x] {r}")
        return

    if args.hunt:
        if not os.environ.get("ANTHROPIC_API_KEY"):
            print("ERROR: ANTHROPIC_API_KEY not set")
            return
        print(f"\nThe Wolf is hunting... (target: {args.hunt})")
        results = wolf.pack_hunt(count=args.hunt, focus=args.focus)
        m = wolf.get_metrics()
        print(f"Done: {len(results)}/{args.hunt} | Rate: {m['approval_rate']} "
              f"| Avg loops: {m['avg_loops_to_approve']:.1f}")
        return

    parser.print_help()


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(name)s] %(levelname)s %(message)s",
                        datefmt="%H:%M:%S")
    main()
