"""Strategy change log (#20, 2026-05-13).

A single source-of-truth for "what changed about strategy X and when?"
Built by mining the git log for commits that touched:
  - config/strategies.py (param changes, retirements, promotions)
  - strategies/<name>.py  (logic changes)

Output: a markdown timeline per strategy. Useful when reviewing a
strategy's recent performance — "did anything actually change between
last week's bad trades and this week's good ones?"

Usage:
    python tools/strategy_change_log.py
    python tools/strategy_change_log.py --strategy bias_momentum
    python tools/strategy_change_log.py --since 2026-04-01
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))


_KNOWN_STRATEGIES = (
    "bias_momentum", "spring_setup", "vwap_pullback", "vwap_band_pullback",
    "vwap_band_reversion", "dom_pullback", "ib_breakout",
    "compression_breakout", "high_precision_only", "noise_area",
    "orb", "opening_session", "footprint_cvd_reversal",
)


def _git(args: list[str]) -> str:
    """Run a git command from ROOT and return stdout (UTF-8), or "" on
    failure. Forces UTF-8 because Windows defaults to cp1252 and emojis
    in commit messages (e.g. our retirement marker 🚫) break the default
    text decoder."""
    try:
        out = subprocess.run(
            ["git", "-C", str(ROOT), *args],
            check=False, capture_output=True,
            encoding="utf-8", errors="replace",
            timeout=30,
        )
        return out.stdout or ""
    except Exception:
        return ""


def collect_strategy_commits(
    strategy_name: str,
    since: str | None = None,
) -> list[dict]:
    """For one strategy, return commits that touched:
       - config/strategies.py with the strategy name in the diff, OR
       - strategies/<strategy_name>.py

    Returns a list of {hash, short_hash, date, subject} dicts, newest first.
    """
    paths_to_track = [
        "config/strategies.py",
        f"strategies/{strategy_name}.py",
    ]
    log_args = [
        "log",
        "--no-merges",
        "--pretty=format:%H|%h|%ad|%s",
        "--date=short",
    ]
    if since:
        log_args.append(f"--since={since}")
    log_args.append("--")
    log_args.extend(paths_to_track)
    raw = _git(log_args)
    if not raw:
        return []
    commits = []
    for line in raw.strip().splitlines():
        parts = line.split("|", 3)
        if len(parts) != 4:
            continue
        full, short, date, subject = parts
        # For config/strategies.py-only commits, confirm the strategy is
        # mentioned in the diff (avoid spammy "I touched the global
        # defaults" commits that don't affect this strategy).
        files = _git(["show", "--name-only", "--pretty=format:", full]).strip().splitlines()
        files = [f for f in files if f]
        touched_strategy_file = any(f == f"strategies/{strategy_name}.py" for f in files)
        if not touched_strategy_file:
            diff = _git([
                "show", "--unified=0", "--pretty=format:", full,
                "--", "config/strategies.py"
            ])
            if strategy_name not in diff:
                continue
        commits.append({
            "hash": full, "short": short, "date": date, "subject": subject,
        })
    return commits


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--strategy",
                    help="Single strategy to report on. Default: all known.")
    ap.add_argument("--since",
                    help="YYYY-MM-DD (git --since format).")
    ap.add_argument("--out", default="-",
                    help="Output path (default: stdout). Pass a path to "
                         "write a markdown file.")
    args = ap.parse_args()

    targets = (args.strategy,) if args.strategy else _KNOWN_STRATEGIES
    L: list[str] = []
    L.append("# Phoenix Strategy Change Log")
    L.append("")
    if args.since:
        L.append(f"_Filter: commits on/after {args.since}_")
    L.append(f"_Generated by `tools/strategy_change_log.py`. "
             f"Source: git log over `config/strategies.py` + "
             f"`strategies/<name>.py`._")
    L.append("")
    for strat in targets:
        commits = collect_strategy_commits(strat, since=args.since)
        L.append(f"## `{strat}`")
        L.append("")
        if not commits:
            L.append("_No commits in window._")
            L.append("")
            continue
        L.append("| date | hash | change |")
        L.append("|---|---|---|")
        for c in commits:
            # Escape any pipe in the subject so the table doesn't break
            subj = c["subject"].replace("|", "\\|")
            L.append(f"| {c['date']} | `{c['short']}` | {subj} |")
        L.append("")
    text = "\n".join(L)
    if args.out == "-":
        # Windows console defaults to cp1252; commit subjects can contain
        # arrows, emoji, etc. Reconfigure stdout to UTF-8 if possible.
        try:
            sys.stdout.reconfigure(encoding="utf-8")
        except Exception:
            pass
        try:
            print(text)
        except UnicodeEncodeError:
            # Last-ditch: strip un-encodable chars rather than crashing.
            print(text.encode("ascii", errors="replace").decode("ascii"))
    else:
        Path(args.out).write_text(text, encoding="utf-8")
        print(f"Wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main() or 0)
